---
  - name: Install Filebeat
    hosts: webservers
    remote_user: azdmin
    become: true
    tasks:

    - name: Download Filebeat .deb
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb

    - name: Install Filebeat .deb
      command: dpkg -i filebeat-7.6.1-amd64.deb

    - name: Copy Filebeat Config File
      ansible.builtin.copy:
        src: /etc/ansible/files/filebeat-config.yml
        dest: /etc/filebeat/filebeat.yml

    - name: Enable System Filebeat
      command: filebeat modules enable system

    - name: Setup Filebeat
      command: filebeat setup

    - name: Start Filebeat Service
      command: service filebeat start

    - name: Enable service filebeat on boot
      systemd:
        name: filebeat
        enabled: yes

    - name: Download and Install Metricbeat
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

    - name: Install Metricbeat
      command: sudo dpkg -i metricbeat-7.6.1-amd64.deb

    - name: Copy Metricbeat Config File
      ansible.builtin.copy:
        src: /etc/ansible/files/metricbeat.yml
        dest: /etc/metricbeat/metricbeat.yml

    - name: Enable and Configure the Docker Module
      command: sudo metricbeat modules enable docker

    - name: Set-up Metricbeat
      command: sudo metricbeat setup

    - name: Start Metricbeat
      command: sudo service metricbeat start

    - name: Enable service Metricbeat on boot
      systemd:
        name: metricbeat
        enabled: yes
